import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core";
import Navbar from "@/components/shared/Navbar";
import CodeProvider from "@/context/CodeContext";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Code Compass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <CodeProvider>
          <CopilotKit runtimeUrl="/api/copilotkit">
            <Navbar/>
            {children}
          </CopilotKit>
        </CodeProvider>
      </body>
    </html>
  );
}
